### ISSUE TITLE
误删问题

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [tinymind/LSUnusedResources#12]
为什么我找出来的资源文件全部都是占用着的文件？
![image](https://cloud.githubusercontent.com/assets/20035768/17549665/e5962eae-5f23-11e6-956c-fd85e9171f02.png)
再提个bug，为什么我在Setting的Resource中设置了imageset之后，再想改为png或是其他类型文件都不管用了？始终是搜索imageset。重启才初始化。

**Comment by tinymind** [comment]
请问你是怎么使用该资源的？
具体一点，比如`aaaa.imageset`这个资源，你在哪个文件已什么方式使用的，方便贴一下代码或者截图吗？谢谢。
第二个 Bug 我先确认一下。

**Comment by Shaunchenzhaojin** [comment]
我用的是一些开源demo做的测试  所以不知道具体怎么使用，但是一旦我将这些资源删除，clean之后编译就会找不到资源文件，指定为png时找出来的结果倒是正确的

**Comment by tinymind** [comment]
麻烦确认一下，这些 imageset 是不是包含在某个 bundle 里？或者你把 demo 的链接发给我测试一下，谢谢。

**Comment by Shaunchenzhaojin** [comment]
github搜索项目LoveFreshBeen

**Comment by tinymind** [comment]
已修复，麻烦重新更新项目代码，或[下载压缩包](https://github.com/tinymind/LSUnusedResources/raw/master/Release/LSUnusedResources.app.zip)。
另外，对于 swift 工程，需要勾选`.swift`的复选框。

**Comment by Shaunchenzhaojin** [comment]
刚刚测试了 已经解决了，谢谢耐心解答，即及时修复
