### ISSUE TITLE
Can't Find out the unused imageset file if the imageset filename is different from the image file in it 

### ISSUE THREAD

**Issue by magicowl** [tinymind/LSUnusedResources#13]
Can't Find out the unused imageset file if the imageset filename is different from the image file in it ！！！！！

**Comment by tinymind** [comment]
So, your imageset name is something like `hello.imageset`, it contains images `world.png`, `world@2x.png`, and how you use it in code?

**Comment by magicowl** [comment]
the Code will be like this:[UIImage  imageNamed:@"world.png"],and by your program ,the hello.imageset file will be identified as unused .

**Comment by tinymind** [comment]
Yes, normally I think people will use with imageset name, like `[UIImage imageNamed:@"hello"]`. 
And I will fix this as soon as possible.

**Comment by magicowl** [comment]
cool.......

**Comment by tinymind** [comment]
Fixed.
