### ISSUE TITLE
 if imageset name is A but contains png with name B, and using as B

### ISSUE THREAD

**Issue by wigl** [tinymind/LSUnusedResources#16]
if imageset name is A but contains png with name B, **the project will can not use name B.**
So not ignore A.imageset.

**Comment by tinymind** [comment]
Like [this](https://github.com/tinymind/LSUnusedResources/issues/13)?

**Comment by wigl** [comment]
Imageset name is  hello.imageset, it contains images world.png, world@2x.png.
In code, if use UIImage *image = [UIImage imageNamed:@"world.png"]; the image will be nil,this is an error usage. And I tested it.

**Comment by tinymind** [comment]
Yes, you are right. I have no idea why [he](https://github.com/tinymind/LSUnusedResources/issues/13) using it in this way.
