### ISSUE TITLE
Exclude feature is not working

### ISSUE THREAD

**Issue by lauracalinoiu** [tinymind/LSUnusedResources#19]
I can not get the Exclude work with my project.
I use Carthage for embedding libraries and since I do not want images from different libraries listed as unused resources, I would want to exclude that.

Thank you for your work!

**Comment by tinymind** [comment]
Thanks for your feedback.
Could you show me how you add exclude folder?

For example, the project directory tree is:
|--MyProject
|----ViewController
|----Resource
|----ThirdParty
|...

If you want to exclude the ThirdParty folder, then you should set Exclude value to `ThirdParty`.

**Comment by lauracalinoiu** [comment]
The problem is that the exclude text field does not save it's value unless user will move the focus to another field. At first, I thought it does not work at all, somehow is counterintuitive. 

![out](https://cloud.githubusercontent.com/assets/948556/21881877/bf8d18b0-d8b0-11e6-9864-537532b33793.gif)

**Comment by tinymind** [comment]
Yes, disable the text filed whit focus status, it's text will be cleared, I don't know why.
I have fixed it, please clone or download [app](https://github.com/tinymind/LSUnusedResources/raw/master/Release/LSUnusedResources.app.zip) again.

**Comment by lauracalinoiu** [comment]
Thanks very much for solving this!
