### ISSUE TITLE
imageset管理的图片搜索不到，只能搜索到文件夹管理的图片

### ISSUE THREAD

**Issue by wangdachui** [tinymind/LSUnusedResources#30]
![1](https://user-images.githubusercontent.com/9476501/30320474-4fe6cb9c-97e5-11e7-9ffe-46d94ad4c326.jpg)
<img width="275" alt="2 2x" src="https://user-images.githubusercontent.com/9476501/30320478-513d533a-97e5-11e7-81a9-7ae405766959.png">
<img width="610" alt="3" src="https://user-images.githubusercontent.com/9476501/30320587-a97f19c0-97e5-11e7-8470-a49da2ba7621.png">
只能搜索到WTTest2.

**Comment by tinymind** [comment]
请问 WTTest1 这个图片，在你的项目中是真的没有被使用吗？
我的项目基本上都是用 imageset 来管理，按道理不会出现这种基本功能的 Bug 的。

**Comment by liwenyou** [comment]
确实找不到

**Comment by tinymind** [comment]
很抱歉，的确有这个 Bug，如果在 `Resource Patterns` 里面勾选了 `json` 类型，就无法正确处理 imageset 管理的图片。
目前已经修复了这个 Bug，请更新代码，或者重新下载 Release 目录下的 app 文件。
谢谢两位， @wangdachui @liwenyou 。
