### ISSUE TITLE
False positives due to SwiftGen provided assets 

### ISSUE THREAD

**Issue by drjasonharrison** [tinymind/LSUnusedResources#32]
We have image assets that are referenced in code as `Asset.imageName.image`. The list of image assets is generated using [SwiftGen](https://github.com/SwiftGen/SwiftGen) using the following command as a build phase:

     swiftgen images "$PROJECT_DIR/appname/Assets.xcassets" -t swift3 \
    --output "$PROJECT_DIR/appname/Constants/Images.swift"

If LSUnusedResources had access to Images.swift it would have the mapping between image filename and code Asset.imageName:

    enum Asset: String {
      case bgBluetooth = "bg-bluetooth"
      case addFab = "add_fab"
      case arrowRight = "arrow_right"
      case batteryLow = "battery_low"
     ....

And then LSUnusedResources could search the source code for "Asset." and then for one of image names.

**Comment by tinymind** [comment]
Hi, please try to change swift patterns from `@"(.+?)"` to `"(.+?)"`.

![image](https://user-images.githubusercontent.com/6042046/31330133-bd8a56ce-aca2-11e7-8400-1e18c747d82a.png)

**Comment by drjasonharrison** [comment]
Yes! that fixes the problem with the false positives! Thank you!

**Comment by tinymind** [comment]
The regular expression is used to match string in source code. In Objective-C, string constants start with `@`, like `NSString *str = @"background";`. But in swift, string constants don't need the `@` symbol.
