### ISSUE TITLE
Mac systemVersion is macOS  Sierrra 10.12.6,but can not build.

### ISSUE THREAD

**Issue by Jakiro-Fan** [tinymind/LSUnusedResources#33]
My Mac systemVersion is  macOS  Sierrra 10.12.6,when I run the project there is a issue appear.The description is "Storyboards are not available before macOS 10.10".Then I change macOS Deployment Target as 10.12,but still appear the same issue.why?What can I do?

**Comment by Jakiro-Fan** [comment]
it‘s ok.The project should modify two places.

**Comment by tinymind** [comment]
Please checkout again.
