### ISSUE TITLE
Default regex wrongly to handle string contains ""

### ISSUE THREAD

**Issue by vin-zhou** [tinymind/LSUnusedResources#35]
The default regex "(.+?)" for .swift/.m .etc  handles string like :

Checkbox(checked: true, titleSelected: "", titleNormal: "", imageSelected: UIImage(named: "cart_agree_checked"), imageNormal: UIImage(named: "cart_agree_unchecked"))

wrongly.
Suggest to use "(.*?)"  instead. @tinymind

**Comment by tinymind** [comment]
Yes, you are right, please checkout the newest code, thanks.
