### ISSUE TITLE
why ignore

### ISSUE THREAD

**Issue by wangdetong** [tinymind/LSUnusedResources#36]
// ignore if the resource file is in xxx/xxx.imageset/; xx/LaunchImage.launchimage; xx/AppIcon.appiconset; xx.bundle/xx
![image](https://user-images.githubusercontent.com/13482840/37913094-a6f7c828-3146-11e8-9ef9-bbf55cd4614c.png)

Maybe there are more unused image in *.imageset or bundle/, why did you ignore?

**Comment by tinymind** [comment]
Please see https://github.com/tinymind/LSUnusedResources/issues/13,  https://github.com/tinymind/LSUnusedResources/issues/16 and https://github.com/tinymind/LSUnusedResources/issues/8.
