### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by Andy1984** [tinymind/LSUnusedResources#4]
In the method  `- (IBAction)onDeleteButtonClicked:(id)sender`</br>
 `[self.resultsTableView removeRowsAtIndexes:indexSet withAnimation:NSTableViewAnimationSlideUp]; ` might be crash. Off the top of my head, it happens a lot when the picture is not in the images.xassets

**Comment by tinymind** [comment]
Fixed it. Please try again.
