### ISSUE TITLE
有关图片引用了 但是扫描出来是无用图片  怎么解决

### ISSUE THREAD

**Issue by MoShenGuo** [tinymind/LSUnusedResources#43]
你好 大神 运行代码确实好用 但是有很大的误差  比如图片资源名称都是[xxx@2x.png](mailto:xxx@2x.png)，但代码中使用的名称是xxx，搜索结果会说[xxx@2x.png](mailto:xxx@2x.png)未被使用,这种问题怎么去解决呢? 望大神指教一下

**Comment by tinymind** [comment]
麻烦详细地描述一下图片存在哪个目录，代码怎么使用图片的，搜索的选项是怎样的？

**Comment by sjsurf** [comment]
图片是存放在ImageSet中，代码中使用也用的是ImageSet的名称，在扫描PNG类型的图片时是显示图片为未使用

**Comment by sjsurf** [comment]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/20354232/57746243-f674cb00-7702-11e9-801c-98620bdf86a6.png">
根据注释来看的话，这里是不是应该在`[self isInImageSetFolder:path]`这里取反

**Comment by tinymind** [comment]
那个地方是有取反的，是不是你本地改了代码？https://github.com/tinymind/LSUnusedResources/blob/master/LSUnusedResources/Model/ResourceFileSearcher.m。

![image](https://user-images.githubusercontent.com/6042046/57843339-abd97880-7800-11e9-8eac-dbd53a996668.png)

**Comment by sjsurf** [comment]
可能是我之前改代码出的问题   抱歉
