### ISSUE TITLE
使用R.swift全部图片都是使用的没办法筛选

### ISSUE THREAD

**Issue by kkkkkks** [tinymind/LSUnusedResources#46]
有什么办法解决接入了R.swift的项目么

**Comment by tinymind** [comment]
是不是 `R.generated.swift` 没纳入扫描范围？

**Comment by tinymind** [comment]
哦，我明白你的意思了，`R.generated.swift` 包含了所有的图片名字，所以本工具认为所有的图片都被使用了。
如果需要支持 R.swift 需要改一下识别方式，我先研究一下。

**Comment by monzy613** [comment]
我们项目的R.generated.swift是在.gitignore里面的， 所有跑LSUnusedResource之前先把R.generated.swift删掉，然后正则改成 (?:R\.image.*)\.([\w_]+)\(\)就能匹配出无用文件了。但是有图片会误删掉 不知道是什么原因。查找出了60个无用文件 其中会有10个左右实际上是用到的，需要手动恢复改一下编译错误。
