### ISSUE TITLE
it can't find image in .bundle file

### ISSUE THREAD

**Issue by maiqili** [tinymind/LSUnusedResources#8]

**Comment by tinymind** [comment]
Generally, images in `.bundle` file will be used in `.a library`, which means, LSUnusedResources can't determine whether it is used, because I can't inject and scan .a file.

**Comment by Farteen** [comment]
@tinymind 
I have a question in ResourceFileInfo.m, line 127
if (![fileType isEqualTo:kSuffixPng]) {
why using "!" here? If remove !, I will get a correct result in .bundle file.

**Comment by tinymind** [comment]
Yes, I can find resource in .bundle file, but have no idea if it is used in somewhere. So I will ignore .bundle file.

**Comment by Farteen** [comment]
@tinymind Thank you for reply. I can make it to satisfy my requirements. And thank you very much.
